### PR TITLE
fix: Execute all gpg2 commands as resource user

### LINKED ISSUE #55: key actions run as root user
The only action that currently executes as the resource user/group is generate. All other commands, such as import, execute as the chef-client user.

### PR DESCRIPTION
**Pull request by tophercullen**
without it, causes all sorts of problems when trying to manage non-root
users

Fix #55

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ramereth** [comment]
@tophercullen it might be good to add something to the test recipe which creates a key using a non-root user and add tests for that as well. Could you do that please?

**Comment by ramereth** [comment]
@tophercullen _nudge_

**Comment by tophercullen** [comment]
I'm not familiar with this testing setup, but I will give it a shot as I have availability.

**Review by Xorima — APPROVED** [review]

**Pull request merged**
